### ISSUE TITLE
Eat your own dogfood: add linkcheck to linkcheck's travis.yml

### ISSUE THREAD

**Issue by ngirard** [Michael-F-Bryan/mdbook-linkcheck#13]
Adding mdbook-linkcheck to this project's own `.travis.yml` file would provide a reference, and a documentation-by-example, on how to integrate linkcheck with Travis.

**Comment by Michael-F-Bryan** [comment]
I don't think we have enough content to actually make this useful. It's just an extra backend to `mdbook` so there isn't any guide per-se. It'd be at most one page on how to enable the plugin, then maybe another page with snippets you can use when adding it to GitLab CI or Travis.

**Comment by Michael-F-Bryan** [comment]
I think I'll close this issue. As previously mentioned we don't really have enough content to make a proper book, and the README already has some instructions for CI so that should be sufficient.

I mainly use `mdbook` for GitLab projects it contains instructions for GitLab CI, but feel free to make a PR if you have a snippet that can be copy-pasted into `travis.yml`.
