### ISSUE TITLE
Support custom HTTP headers

### ISSUE THREAD

**Issue by CreepySkeleton** [Michael-F-Bryan/mdbook-linkcheck#22]
Some websites (for example crates.io) require certain HTTP headers (for example `Accept`) to be passed in order to process the request properly.

I propose to allow user to specify the needed headers for URLs matching a certain regexp:
```toml
[output.linkcheck]
headers = {
  "https?://crates.io/crate/.*" = "Accept: text/html",
  "example,com" = "Accept: text/xml"
}
```

**Comment by Michael-F-Bryan** [comment]
This sounds like a good idea. I'm guessing we can use [the `#[serde(with = "...")]` trick](https://github.com/Michael-F-Bryan/mdbook-linkcheck/blob/674f56a39ee4eb54ba88d640eadbc91f071f9b41/src/config.rs#L16) to parse a `Table` into a list of regex patterns and headers and from there we may need to pull request generation out into its own function instead of using [the `Client::get()` helper](https://github.com/Michael-F-Bryan/mdbook-linkcheck/blob/674f56a39ee4eb54ba88d640eadbc91f071f9b41/src/validate.rs#L268) so patterns can be applied.

It should also easy to extend to interpolate environment variables for non-public endpoints (e.g. with an `Authorization: Basic $GITHUB_TOKEN`) if people were interested.
