### ISSUE TITLE
release it as a binary on github

### ISSUE THREAD

**Issue by m040601** [Michael-F-Bryan/mdbook-linkcheck#8]
This is such a great addon to the (great) mdbook.
Thank you for your work.
Would it be possible to release it as a binary ? At least compiled for x86_64.
It would make it much easier to release this as a precompiled package for arch linux and other distros. It would make much easier for people who dont have the entire rust distribution to quickly try it out.

**Comment by Michael-F-Bryan** [comment]
Binaries are available on the [Releases](https://github.com/Michael-F-Bryan/mdbook-linkcheck/releases) page for 64-bit Windows, Linux, and MacOS. 

Otherwise if you've got docker installed, you can use the [michaelfbryan/mdbook-docker-image](https://hub.docker.com/r/michaelfbryan/mdbook-docker-image).docker image. It's what we use in CI at work for generating internal docs and comes with things like `mdbook` and `mdbook-linkcheck` pre-installed.
